# Generated by Django 3.2.7 on 2021-09-10 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('short_form', models.URLField()),
                ('shortened_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Processing'), (2, 'Active'), (3, 'Rejected')])),
                ('shortened_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_ip', models.GenericIPAddressField()),
                ('is_bot', models.BooleanField(default=False)),
                ('visit_revenue', models.FloatField(verbose_name=0.0)),
                ('visited_link', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='link.link')),
            ],
        ),
    ]
